name: Build release

on:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Grab release artifact
      run: cp target/release/oputil ./oputil-${{ matrix.os }}
      if: ${{ matrix.os != 'windows' }}
    - name: Grab release artifact - windows
      run: cp target/release/oputil.exe ./oputil-${{ matrix.os }}.exe
      if: ${{ matrix.os == 'windows' }}
    - uses: actions/upload-artifact@v3
      if: ${{ matrix.os != 'windows' }}
      with:
        name: oputil-${{ matrix.os }}
        path: oputil-${{ matrix.os }}
        retention-days: 1
    - uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows' }}
      with:
        name: oputil-${{ matrix.os }}.exe
        path: oputil-${{ matrix.os }}.exe
        retention-days: 1
  create_gh_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git log
      run: echo "# Changes" > changes.md && git log $(git describe --tags --abbrev=0 ${{ github.ref_name }}^)..${{ github.ref_name }} --pretty=format:"[%h] %s" >> changes.md
    - uses: actions/download-artifact@v3
    - uses: ncipollo/release-action@v1
      with:
        name: oputil ${{ github.ref_name }}
        bodyFile: "changes.md"
        artifacts: "oputil-macos,oputil-ubuntu,oputil-windows.exe"